version: "2.20"

# service want to run
services:
  postgresql:
    image: postgres
    container_name: postgres-server
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: express-restapi
    volumes:
      - express-restapi-postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432 # host_port:container_port
    networks:
      - express-restapi-networks

  redis:
    image: redis/redis-stack # for development (include redis insight)
    #image: redis/redis-stack-server # for production
    container_name: redis-server
    restart: unless-stopped
    environment:
      REDIS_ARGS: "--requirepass 12345678"
    ports:
      - 6379:6379 # redis
      - 8001:8001 # redis insight (web view)
    networks:
      - express-restapi-networks
    volumes:
      - express-restapi-redis:/data:rw

  express-restapi:
    image: asidikrdn/express-restapi:v1.1.0
    container_name: express-restapi
    restart: unless-stopped
    command: sh -c "npm run migrate-up && npm run seed-up && npm start"
    depends_on:
      - postgresql
      - redis
    environment:
      PROD_DB_HOST: postgresql
      PROD_DB_PORT: 5432
      PROD_DB_USER: user
      PROD_DB_PASSWORD: 12345678
      PROD_DB_NAME: express-restapi
      PORT: 5000
      JWT_SECRET: jwtsecret
      SMTP_HOST: smtp.gmail.com
      SMTP_PORT: 587
      SENDER_NAME: "Express REST API <express-restapi@mail.com>"
      AUTH_EMAIL: yourmail@mail.com
      AUTH_PASSWORD: 12345678
      REDIS_URL: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: 12345678
      SUPERADMIN_EMAIL: superadmin@mail.com
      SUPERADMIN_PASSWORD: 12345678
      ORIGIN_ALLOWED: "*"
      NODE_ENV: production
    volumes:
      - express-restapi-uploads:/uploads
    ports:
      - 5055:5000
    networks:
      - express-restapi-networks

networks:
  # use existing external networks
  # internal-networks:
    # name: internal-networks
    # external: true
  express-restapi-networks:
    name: express-restapi-networks
    driver: bridge

volumes:
  express-restapi-postgres:
  express-restapi-redis:
  express-restapi-uploads:
